version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: goal-tracker-postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - goal-tracker-network

  # pgAdmin for database management UI
  pgadmin:
    image: dpage/pgadmin4
    container_name: goal-tracker-pgadmin
    ports:
      - "5050:80"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - goal-tracker-network

  backend:
    build: ./backend
    container_name: goal-tracker-backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - goal-tracker-network

volumes:
  postgres_data:

networks:
  goal-tracker-network:
    driver: bridge

