export const DEFAULT_STATUSES = ['TODO', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'ON_HOLD'];

export type GoalStatus = 'TODO' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED' | 'ON_HOLD';

export const DEFAULT_CATEGORIES = ['PERSONAL', 'WORK', 'HEALTH', 'FINANCIAL', 'EDUCATION', 'FAMILY', 'SOCIAL', 'SPIRITUAL', 'OTHER'];
