export enum GoalCategory {
  PERSONAL = 'PERSONAL',
  WORK = 'WORK',
  HEALTH = 'HEALTH',
  FINANCIAL = 'FINANCIAL',
  EDUCATION = 'EDUCATION',
  FAMILY = 'FAMILY',
  SOCIAL = 'SOCIAL',
  SPIRITUAL = 'SPIRITUAL',
  OTHER = 'OTHER'
}
